# Generated by Django 5.2.5 on 2025-08-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture_url',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
